/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team14.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.List;

import edu.duke.ece651.team14.shared.Communicator;
import edu.duke.ece651.team14.shared.GameModel;
import edu.duke.ece651.team14.shared.MyName;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
  GUIClientPlayer client;

  GameModel model;

  /**
   * Returns message, verifies that Client App class was created properly
   *
   * @return String
   */
  public String getMessage() {
    return "Hello from the client for " + MyName.getName();
  }

  @Override
  public void init() throws IOException {
    List<String> params = getParameters().getRaw();
    String hostName = params.get(0);
    int port = Integer.parseInt(params.get(1));
    Socket clientSocket = new Socket(hostName, port);
    Communicator comm = new Communicator(clientSocket.getOutputStream(), clientSocket.getInputStream());
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    model = new GameModel(null, 0, 0, 0, 1);
    ClientChatRoom chatRoom = new ClientChatRoom(hostName);
    this.client = new GUIClientPlayer(chatRoom, model, clientSocket, comm, input, System.out);
  }

  @Override
  public void start(Stage stage) throws Exception {
    this.client.setStage(stage);
    this.client.loginPhase();
  }

  // ./gradlew :client:run --args "vcm-xxxxx.vm.duke.edu [port_num]"
  public static void main(String[] args) {
    launch(args[0], args[1]);
  }
}
